### ISSUE TITLE
Running on raspberry pi/32-bit systems

### ISSUE THREAD

**Issue by hailang8635** [sbencoding/wdfs#6]
clang --version
clang version 7.0.1-8+rpi3 (tags/RELEASE_701/final)

but compile is wrong
```
pi@raspberrypi:~/workspce/wdfs/build $ sh build.sh 
In file included from ../src/wd_bridge.cpp:1:
In file included from ../src/wdfs.h:4:
In file included from ../src/Fuse.h:33:
In file included from /usr/include/fuse3/fuse.h:19:
/usr/include/fuse3/fuse_common.h:778:13: error: bit-field '_fuse_off_t_must_be_64bit' has negative width (-1)
        { unsigned _fuse_off_t_must_be_64bit:((sizeof(off_t) == 8) ? 1 : -1); };
                   ^
../src/wd_bridge.cpp:26:35: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
    char *fakeArgs[3] = {argv[0], "-f", mount_path};
                                  ^
In file included from ../src/wd_bridge.cpp:1:
In file included from ../src/wdfs.h:4:
../src/Fuse.h:163:27: error: assigning to 'int (*)(const char *, int, void *, struct fuse_file_info *, unsigned int, void *)' from
      incompatible type 'Fusepp::t_ioctl' (aka 'int (*)(const char *, unsigned int, void *, struct fuse_file_info *, unsigned int, void
      *)'): type mismatch at 2nd parameter ('int' vs 'unsigned int')
      operations_.ioctl = T::ioctl;
                          ^~~~~~~~
../src/Fuse.h:104:7: note: in instantiation of member function 'Fusepp::Fuse<WdFs>::load_operations_' requested here
      load_operations_();
      ^
../src/wdfs.h:12:9: note: in instantiation of member function 'Fusepp::Fuse<WdFs>::Fuse' requested here
        WdFs() {}
        ^
1 warning and 2 errors generated.
In file included from ../src/wdfs.cpp:1:
In file included from ../src/wdfs.h:4:
In file included from ../src/Fuse.h:33:
In file included from /usr/include/fuse3/fuse.h:19:
/usr/include/fuse3/fuse_common.h:778:13: error: bit-field '_fuse_off_t_must_be_64bit' has negative width (-1)
        { unsigned _fuse_off_t_must_be_64bit:((sizeof(off_t) == 8) ? 1 : -1); };
                   ^
../src/wdfs.cpp:356:66: warning: format specifies type 'int' but the argument has type 'off_t' (aka 'long') [-Wformat]
    LOG("[write]: Writing %d bytes of data at %d to %s\n", size, offset, file_path);
                                              ~~                 ^~~~~~
                                              %ld
../src/wdfs.cpp:14:40: note: expanded from macro 'LOG'
    #define LOG(fmt,...) printf(fmt, ##__VA_ARGS__)
                                ~~~    ^~~~~~~~~~~
../src/wdfs.cpp:578:67: warning: format specifies type 'int' but the argument has type 'off_t' (aka 'long') [-Wformat]
    LOG("[read]: Requesting content for file %s [%d:%d]\n", path, offset, offset + size);
                                                 ~~               ^~~~~~
                                                 %ld
../src/wdfs.cpp:14:40: note: expanded from macro 'LOG'
    #define LOG(fmt,...) printf(fmt, ##__VA_ARGS__)

```

**Comment by sbencoding** [comment]
Hello!
Thank you for checking out the project, sorry for any inconveniences.  
I've just merged the `dev` branch with `master`, which solves the problems you ran into, I've also ran this release on the raspberry pi, and it worked.  
To solve the error do the following:
1. navigate into the project folder
2. make sure you're on the `master` branch and execute `git pull origin master`, this will pull the latest changes to the `master` branch
3. README.md was updated with dependencies for debian(raspberri pi), please execute the following command: `sudo apt-get install curl libcurl4 libcurl4-openssl-dev` for CURL and `sudo apt-get install fuse3 libfuse3-3 libfuse3-dev` for FUSE
4. navigate into the `build/` directory and execute `build.sh`.
In this release the build script allows you to specify the compiler to use: `gcc`/`clang` as the first argument.
The second argument is the system architecture. The default value of `64` should be good for most systems, but the raspberry pi is a 32-bit system, so specify `32` as the second argument.
So to build for the raspberry pi with gcc, your would execute the following command:
`build.sh gcc 32`

These are the changes you have to make. They're all documented in the new README.md file, so you could also follow through it if you'd prefer that.

If you run into additional errors, feel free to post them here, and I'll try to help as much as I can.

**Comment by sbencoding** [comment]
The new build system is much more user friendly than the `*.sh` scripts, it also automatically detects if it's being ran on a 32-bit system and sets additional compile flags accordingly.

Closing this issue for now, but if the problem persists or anyone encounters this again we could discuss it in an other issue, in the context of the new build system (using `make`)
